// Execute this async page function with the session's Playwright runner.
async (page) => {
  const base = 'http://127.0.0.1:4600/prototype/path-lab.html';
  const assert = (value, message) => { if (!value) throw new Error(message); };
  const image = () => page.locator('#path-canvas').evaluate(canvas => canvas.toDataURL());
  const ready = () => page.locator('#path-canvas[data-ready="true"]').waitFor({ timeout: 5000 });
  const stop = async age => {
    await page.locator(`[data-stop="${age}"]`).click();
    await page.waitForFunction(age => document.querySelector('#path-canvas').dataset.age === String(age)
      && document.querySelector('#lab-status').dataset.busy === 'false', age);
  };
  const change = async (field, value) => {
    await page.locator(`#${field}`).fill(String(value));
    await page.locator(`#${field}`).dispatchEvent('input');
    await page.waitForFunction(() => document.querySelector('#lab-status').dataset.busy === 'false');
  };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base);
  assert(await page.locator('[data-mode="organic"]').count() === 1, 'The visual must offer a distinct Organic comparison');
  await ready();
  assert(await page.locator('#path-canvas').evaluate(c => c.getBoundingClientRect().width > innerWidth * 0.65), 'The standalone diagram must own most of the page');
  assert(await page.locator('#path-canvas').evaluate(c => c.width >= c.getBoundingClientRect().width * 2 - 1), 'The new page must keep high-resolution strokes');
  assert(await page.locator('#path-canvas').getAttribute('data-age') === '0', 'The initial view must begin at birth');
  assert(await page.locator('#todayBurst').isDisabled(), 'Today branching is available once a time is selected');
  assert(await page.locator('#todayBurst-help').innerText().then(text => /select|choose|pick/i.test(text)), 'The disabled Today control must explain how to enable it');
  assert(await page.locator('#timeline-age').getAttribute('max') === '70', 'Selection stops at seventy');
  await page.locator('#timeline-age').fill('35');
  await page.locator('#timeline-age').dispatchEvent('input');
  await page.waitForFunction(() => document.querySelector('#path-canvas').dataset.age === '25'
    && document.querySelector('#lab-status').dataset.busy === 'false');
  assert(await page.locator('#timeline-age').getAttribute('aria-valuenow') === '25', 'Assistive tech hears age, not warped slider position');
  await page.locator('#timeline-age').press('ArrowRight');
  await page.waitForFunction(() => document.querySelector('#path-canvas').dataset.age === '26'
    && document.querySelector('#lab-status').dataset.busy === 'false');
  await page.locator('#timeline-age').press('End');
  await page.waitForFunction(() => document.querySelector('#path-canvas').dataset.age === '70'
    && document.querySelector('#lab-status').dataset.busy === 'false');
  await stop(0);
  const opening = await image();
  await page.locator('[data-group="Shape"]').click();
  await change('crowdingStrength', 1.15);
  assert(await page.locator('#crowdingStrength-value').innerText() === '1.15', 'Parameter readouts must preserve slider precision');
  await stop(40);
  assert(await page.locator('#path-canvas').getAttribute('data-age') === '40', 'A stop must update Today');
  const atForty = await image();
  await page.locator('[data-mode="organic"]').click();
  await page.waitForFunction(() => document.querySelector('#lab-status').dataset.busy === 'false');
  const organicForty = await image();
  assert(organicForty !== atForty, 'Organic must generate a genuinely different field, not just change its label');
  await page.reload();
  await ready();
  assert(await page.locator('[data-mode="organic"]').getAttribute('aria-pressed') === 'true', 'The algorithm selection must survive reload');
  assert(await image() === organicForty, 'An Organic drawing must replay exactly from the URL');
  await page.locator('[data-mode="paced"]').click();
  await page.waitForFunction(() => document.querySelector('#lab-status').dataset.busy === 'false');
  assert(await image() === atForty, 'Switching back must restore the Paced drawing exactly');
  assert(atForty !== opening, 'The timeline stop must actually change the visible path');
  await stop(12);
  await stop(40);
  assert(await image() === atForty, 'Returning to a stop must reproduce the same route');
  await page.locator('[data-group="Branching"]').click();
  assert(await page.locator('#todayBurst').isEnabled(), 'Selecting a time enables the fresh-fan control');
  assert(await page.locator('#network-summary').innerText().then(text => /Today fan:/.test(text)), 'The selected age must have a fresh generated fan');
  await change('todayBurst', 0);
  assert(await image() !== atForty, 'Removing the Today boost must change the actual future generation');
  await change('todayBurst', 0.85);
  assert(await image() === atForty, 'Restoring Today burst must reproduce the same fan');
  await change('burstSpan', 1);
  const shortBoost = await image();
  await change('burstSpan', 12);
  assert(await image() !== shortBoost, 'Boost duration must change the Paced drawing with an active boost');
  await change('burstSpan', 5);
  assert(await image() === atForty, 'Restoring boost duration must replay the field');
  await page.locator('[data-group="Forks"]').click();
  assert(await page.locator('#first-fork-actual').innerText().then(text => /[2-8] branches/.test(text)), 'The first-fork range must expose the actual generated count');
  assert(await page.getByRole('group', { name: 'First fork', exact: true }).locator('input').count() === 2,
    'The first-fork bounds must be grouped as one accessible range');
  await change('firstChildrenMin', 6);
  assert(await page.locator('#firstChildrenMax').inputValue() === '6', 'Raising a minimum above its maximum must keep the range valid');
  assert(await page.locator('#first-fork-actual').innerText().then(text => /6 branches/.test(text)), 'The generated first fork must honor the raised minimum');
  await change('firstChildrenMax', 3);
  assert(await page.locator('#firstChildrenMin').inputValue() === '3', 'An exact three-branch range must remain valid');
  assert(await page.locator('#first-fork-actual').innerText().then(text => /3 branches/.test(text)), 'An exact smaller range must actually generate fewer first-fork children');
  await change('firstChildrenMin', 4);
  await change('firstChildrenMax', 5);
  assert(await image() === atForty, 'Restoring branch counts must reproduce the field');
  await change('forkSpread', 60);
  assert(await image() !== atForty, 'Fork spread must change the geometry, not only a label');
  await change('forkSpread', 120);
  assert(await page.locator('#forkSpread-value').innerText() === '120°', 'The fork aperture must read clearly in degrees');
  assert(await image() === atForty, 'Restoring the 120-degree spread must replay the same field');
  await change('wideForkLevels', 3);
  assert(await image() !== atForty, 'Additional wide opening rounds must change actual branch geometry');
  await change('wideForkLevels', 1);
  assert(await image() === atForty, 'Restoring opening rounds must replay the same field');
  await change('laterBranchSpacing', 6);
  const tighterLater = await image();
  assert(tighterLater !== atForty, 'Later spacing must affect the count-scaled fans');
  await page.reload();
  await ready();
  await page.locator('[data-group="Forks"]').click();
  assert(await page.locator('#laterBranchSpacing').inputValue() === '6', 'Reload must preserve later branch spacing');
  assert(await image() === tighterLater, 'Reload must reproduce the tuned fan geometry');
  await change('laterBranchSpacing', 12);
  assert(await image() === atForty, 'Restoring later spacing must restore the original drawing');
  const futureEnds = () => page.locator('#network-summary').innerText().then(text => Number(text.match(/Today fan: (\d+)/)?.[1]));
  const middleAgeEnds = await futureEnds();
  await stop(60);
  assert(await futureEnds() < middleAgeEnds, 'Late-life futures must be structurally fewer, not just a squeezed copy');
  await stop(70);
  assert(await page.locator('#network-summary').innerText().then(text => !/Today fan:/.test(text)), 'No future is drawn beyond seventy');
  await stop(40);
  await page.locator('[data-group="Branching"]').click();
  await change('splitProbability', 0);
  assert(await image() !== atForty, 'A generation control must change the actual drawing');
  assert(await page.locator('#network-summary').innerText().then(text => /1 branch end\b/.test(text)), 'Zero split chance must produce one branch, not silently retain a capped tree');
  await page.locator('#reset-lab').click();
  await page.waitForFunction(() => document.querySelector('#lab-status').dataset.busy === 'false');
  await stop(40);
  assert(await image() === atForty, 'Reset must restore the drawing and seed exactly');
  await page.locator('[data-group="Style"]').click();
  await change('lineWidth', 3.4);
  const thick = await image();
  assert(thick !== atForty, 'Line weight must visibly update');
  await page.locator('#path-variant').selectOption('fading');
  assert(await image() !== thick, 'Fading must visibly change untaken paths');
  await page.reload();
  await ready();
  await page.locator('[data-group="Style"]').click();
  assert(await page.locator('#lineWidth').inputValue() === '3.4', 'Reload must restore the tuned value');
  assert(await page.locator('#path-variant').inputValue() === 'fading', 'Reload must restore the visibility treatment');
  assert(await page.locator('#path-canvas').getAttribute('data-age') === '40', 'Reload must preserve Today');
  await page.locator('#how-it-works').click();
  assert(await page.locator('#algorithm-dialog').isVisible(), 'The algorithm explanation must be available on this page');
  assert(await page.locator('#organic-rule').isVisible(), 'The Organic per-line rule must be explained on the page');
  await page.keyboard.press('Escape');
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('denied'); } } }); });
  await page.locator('#copy-settings').click();
  assert(await page.locator('#settings-dialog').isVisible(), 'Denied clipboard access must offer a manual copy fallback');
  const exported = JSON.parse(await page.locator('#settings-output').inputValue());
  assert(exported.settings.lineWidth === 3.4 && exported.age === 40, 'Copied settings must reproduce both the drawing and time');
  await page.keyboard.press('Escape');
  for (const viewport of [{width:1133,height:744}, {width:744,height:1133}]) {
    await page.setViewportSize(viewport);
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'The visual lab overflows horizontally on iPad mini');
    assert(await page.locator('#path-canvas').evaluate(c => c.getBoundingClientRect().height > 400), 'The map must stay useful on tablet');
    if (viewport.width === 744) assert(await page.locator('#edgeFade').evaluate(input => input.getBoundingClientRect().bottom < innerHeight), 'Portrait tuning must keep the map and all four current controls visible together');
  }
  assert(errors.length === 0, `Browser errors: ${errors.join('; ')}`);
  return { passed: ['visual-only layout', 'deterministic timeline stops', 'fresh Today fan control', 'live generation and reset', 'live style and URL restoration', 'algorithm explanation', 'copy fallback', 'desktop and both tablet layouts'], errors };
}
